name: Docker Image CI in Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./docker/build.sh

  run-image:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Run the Docker image
      run: docker run stm32-workspace