name: Docker Image CI in Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: ./docker/build.sh

      - name: Test Build STM32 Flash Image
        run: docker run -v $(pwd):/opt/project \
              -it --rm  \
              --hostname stm32-workspace \
              --workdir /opt/project \
              stm32-workspace:latest ./build.sh
