name: Docker Image CI in Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: ./docker/build.sh

      - name: Test Build STM32 Flash Image
        run: ./docker/run.sh ./build.sh
